---
- name: "check elasticsearch version"
  uri:
    url: "http://{{ maint_es_server_ip }}:{{ maint_es_server_port }}"
  register: "es_response"

- name: "ES server facts"
  set_fact:
    es_version: "{{ es_response.json.version.number }}"

- debug:
    msg: "ES version number is {{ es_version }}"

- fail:
    msg: "ES version <1.0. Repos/Snapshots not supported"
  when: "es_version is version('1.0', '<')"

- debug:
    msg: "ES version >1.6 . path.repo required"
  when: "es_version is version('1.6', '>=')"

- name: "add path.repo var to elasticsearch.yml"
  lineinfile:
    dest: "/etc/elasticsearch/elasticsearch.yml"
    regexp: "^path.repo:"
    line: "path.repo: [\"{{ maint_es_repo_path }}\"]"
    backup: "yes"
    owner: "elasticsearch"
    group: "elasticsearch"
  when: "es_version is version('1.6', '>=')"
  notify: "restart elasticsearch"

- name: "create directory to hold repository"
  file:
    path: "{{ maint_es_repo_path }}"
    state: "directory"
    mode: "0755"
    owner: "elasticsearch"
    group: "elasticsearch"

- name: "flush to restart elasticsearch if there were config changes"
  meta: "flush_handlers"

- name: "wait until elasticsearch port is open (to avoid errors when it was restarted)"
  wait_for:
    host: "{{ maint_es_server_ip }}"
    port: "{{ maint_es_server_port }}"

- name: "add repository to elasticsearch"
  uri:
    url: "http://{{ maint_es_server_ip }}:{{ maint_es_server_port }}/_snapshot/{{ maint_es_repo_name }}"
    method: "PUT"
    body:
      type: "fs"
      settings:
        location: "{{ maint_es_repo_path }}"
    body_format: "json"

